spring:
  application:
    name: Product

  datasource:
    url: jdbc:mysql://${DB_HOST:mysql}:${DB_PORT:3306}/${DB_NAME:ms_product_db}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:1234}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health, info, metrics, loggers, beans, shutdown
    #        include: "*"

  endpoint:
    health:
      show-details: always
    shutdown:
      enabled: true

info:
  app:
    name: Product
    version: 0.0.1
    owner: Saddab

server:
  port: 8081