spring:
  application:
    name: order
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      fail-fast: false

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  endpoint:
    busrefresh:
      access: unrestricted
