spring:
  application:
    name: gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: lb://USER
              predicates:
                - Path=/api/users/**

            - id: product-service
              uri: lb://PRODUCT
              predicates:
                - Path=/api/products/**

            - id: order-service
              uri: lb://ORDER
              predicates:
                - Path=/api/orders/**, /api/cart/**

server:
  port: 8080
