spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/ms_order_db
    username: postgres
    password: 1234

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest


  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

management:
  endpoint:
    busrefresh:
      access: unrestricted
    health:
      show-details: always
    shutdown:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"

info:
  app:
    name: Order
    version: 0.0.1
    owner: Saddab

eureka:
  client:
  service-url:
    defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true


server:
  port: 8083

