spring:
  mongodb:
    host: localhost
    database: ms_user_db
    port: 27017

  rabbitmq:
    enabled: false

management:
  endpoint:
    busrefresh:
      access: unrestricted
    health:
      show-details: always
    shutdown:
      enabled: true

  endpoints:
    web:
      exposure:
        include: "*"

  health:
    rabbit:
      enabled: false

info:
  app:
    name: User
    version: 0.0.1
    owner: Saddab

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

server:
  port: 8082
