### ADD USER

POST http://localhost:8080/api/users/add
Content-Type: application/json

{
  "firstName": "John",
  "lastName": "Doe",
  "email": "john.doe@example.com",
  "phone": "+1-555-123-4567",
  "role": "CUSTOMER",
  "address": {
    "street": "221B Baker Street",
    "city": "London",
    "state": "Greater London",
    "country": "UK",
    "zipcode": "NW1 6XE"
  }
}

###
